### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by xZeroMCPE** [LuaMine/LuaMine#1]
Hello, can i help contribute to this project? as a member

**Comment by NidPlays** [comment]
@xZeroMCPE how do I run this server type?

**Comment by Dog2puppy** [comment]
@xZeroMCPE Sure. 
@NidPlays It runs luvit, but its not functional yet.

**Comment by xZeroMCPE** [comment]
@Dog2puppy I don't have right access...

**Comment by Dog2puppy** [comment]
You should. Hmm....

**Comment by xZeroMCPE** [comment]
now i do.  But can't edit descriptions ect

**Comment by Dog2puppy** [comment]
Ill look into it.

**Comment by xZeroMCPE** [comment]
works now for this repo only.

**Comment by Dog2puppy** [comment]
??

**Comment by xZeroMCPE** [comment]
like i only have admin access to this repo only.. not others
